using Suivi_Elec_Maison.Database;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using static Suivi_Elec_Maison.Database.DatabaseHelper;

namespace Suivi_Elec_Maison
{
    public partial class MeasurementsWindow : Window
    {
        private DataTable? _currentData;
        private PrixElecTarif? _currentTarif;

        public MeasurementsWindow()
        {
            InitializeComponent();
            Loaded += MeasurementsWindow_Loaded;
            BtnRefresh.Click += async (s, e) => await LoadMeasuresAsync();
            CbMonth.SelectionChanged += CbMonth_SelectionChanged;
            DataGridMeasures.AutoGeneratedColumns += (s, e) => AdjustColumns();
        }

        private async void MeasurementsWindow_Loaded(object? sender, RoutedEventArgs e)
            => await LoadMeasuresAsync();

        // ── Chargement initial ───────────────────────────────────────────────
        private async Task LoadMeasuresAsync()
        {
            try
            {
                BtnRefresh.IsEnabled = false;
                var dt = await DatabaseHelper.GetMeasuresAsync(5000);

                // Formatage colonne Jour → yyyy/MM/dd
                var jourCol = dt.Columns.Cast<DataColumn>()
                    .FirstOrDefault(c => string.Equals(c.ColumnName, "Jour",
                        StringComparison.OrdinalIgnoreCase))?.ColumnName;

                if (!string.IsNullOrEmpty(jourCol))
                {
                    const string tmpName = "Jour_formatted_tmp";
                    dt.Columns.Add(tmpName, typeof(string));

                    foreach (DataRow r in dt.Rows)
                    {
                        try
                        {
                            var val = r[jourCol];
                            if (val == DBNull.Value) { r[tmpName] = string.Empty; continue; }
                            r[tmpName] = val is DateTime dtv
                                ? dtv.ToString("yyyy/MM/dd")
                                : DateTime.TryParse(val.ToString(), out var p)
                                    ? p.ToString("yyyy/MM/dd")
                                    : val.ToString();
                        }
                        catch { r[tmpName] = string.Empty; }
                    }

                    dt.Columns.Remove(jourCol);
                    dt.Columns[tmpName].ColumnName = "Jour";
                }

                _currentData = dt;

                // ── Remplissage CbYear ──
                CbYear.SelectionChanged -= CbYear_SelectionChanged;
                CbYear.Items.Clear();
                CbYear.Items.Add("Tous");

                var years = new SortedSet<string>();
                if (_currentData.Columns.Contains("Jour"))
                    foreach (DataRow r in _currentData.Rows)
                    {
                        var v = r["Jour"]?.ToString();
                        if (!string.IsNullOrEmpty(v) && v.Length >= 4)
                            years.Add(v.Substring(0, 4));
                    }
                foreach (var y in years) CbYear.Items.Add(y);
                CbYear.SelectedIndex = 0;
                CbYear.SelectionChanged += CbYear_SelectionChanged;

                // ── Remplissage CbMonth (toutes années) ──
                RefreshMonthCombo(null);

                DataGridMeasures.ItemsSource = _currentData.DefaultView;
                AdjustColumns();

                // Calcul initial
                var selYear = CbYear.SelectedItem as string ?? "Tous";
                var selMonth = CbMonth.SelectedItem as string ?? "Tous";
                var dvInit = BuildDataView(selYear, selMonth);
                await RefreshAllStatsAsync(dvInit, selYear, selMonth);
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Impossible de charger les mesures : {ex.Message}",
                    "Erreur", MessageBoxButton.OK, MessageBoxImage.Error);
            }
            finally
            {
                BtnRefresh.IsEnabled = true;
            }
        }

        // ── Changement d'année ───────────────────────────────────────────────
        private async void CbYear_SelectionChanged(object? sender, SelectionChangedEventArgs e)
        {
            if (_currentData == null) return;

            var selYear = CbYear.SelectedItem as string ?? "Tous";

            // Reconstruire les mois filtrés sur l'année choisie
            CbMonth.SelectionChanged -= CbMonth_SelectionChanged;
            RefreshMonthCombo(selYear == "Tous" ? null : selYear);
            CbMonth.SelectionChanged += CbMonth_SelectionChanged;

            var selMonth = CbMonth.SelectedItem as string ?? "Tous";
            var dv = BuildDataView(selYear, selMonth);

            DataGridMeasures.ItemsSource = dv;
            AdjustColumns();
            await RefreshAllStatsAsync(dv, selYear, selMonth);
        }

        // ── Changement de mois ───────────────────────────────────────────────
        private async void CbMonth_SelectionChanged(object? sender, SelectionChangedEventArgs e)
        {
            if (_currentData == null) return;

            var selYear = CbYear.SelectedItem as string ?? "Tous";
            var selMonth = CbMonth.SelectedItem as string ?? "Tous";
            var dv = BuildDataView(selYear, selMonth);

            DataGridMeasures.ItemsSource = dv;
            AdjustColumns();
            await RefreshAllStatsAsync(dv, selYear, selMonth);
        }

        // ── Helpers filtrage ─────────────────────────────────────────────────

        /// <summary>Reconstruit CbMonth selon l'année sélectionnée (null = toutes).</summary>
        private void RefreshMonthCombo(string? filterYear)
        {
            CbMonth.Items.Clear();
            CbMonth.Items.Add("Tous");

            var months = new SortedSet<string>();
            if (_currentData!.Columns.Contains("Jour"))
                foreach (DataRow r in _currentData.Rows)
                {
                    var v = r["Jour"]?.ToString();
                    if (string.IsNullOrEmpty(v) || v.Length < 7) continue;
                    if (filterYear != null && !v.StartsWith(filterYear)) continue;
                    months.Add(v.Substring(0, 7)); // yyyy/MM
                }

            foreach (var m in months) CbMonth.Items.Add(m);
            CbMonth.SelectedIndex = 0;
        }

        /// <summary>Construit la DataView en appliquant les filtres année + mois.</summary>
        private DataView BuildDataView(string selYear, string selMonth)
        {
            try
            {
                if (selMonth != "Tous")
                    return new DataView(_currentData!) { RowFilter = $"Jour LIKE '{selMonth}%'" };

                if (selYear != "Tous")
                    return new DataView(_currentData!) { RowFilter = $"Jour LIKE '{selYear}%'" };

                var dv = _currentData!.DefaultView;
                dv.RowFilter = string.Empty;
                return dv;
            }
            catch
            {
                return _currentData!.DefaultView;
            }
        }

        // ── Calculs ──────────────────────────────────────────────────────────
        private async Task RefreshAllStatsAsync(DataView dv, string selYear, string selMonth)
        {
            try
            {
                if (selMonth != "Tous"
                    && selMonth.Length == 7
                    && int.TryParse(selMonth.Substring(0, 4), out int y)
                    && int.TryParse(selMonth.Substring(5, 2), out int m))
                {
                    // Mois précis → tarif du mois
                    _currentTarif = await DatabaseHelper.GetTarifForMonthAsync(y, m);
                }
                else if (selYear != "Tous"
                    && int.TryParse(selYear, out int year))
                {
                    // Année entière → tarif le plus fréquent de l'année
                    _currentTarif = await DatabaseHelper.GetTarifForYearAsync(year);
                }
                else
                {
                    // Tous → tarif le plus récent
                    _currentTarif = await DatabaseHelper.GetLatestTarifAsync();
                }
            }
            catch { _currentTarif = null; }

            RefreshSynthese(dv);
            RefreshRatios(dv);
            RefreshSimulations(dv);
        }

        // ── Tableau 1 : synthèse ─────────────────────────────────────────────
        private void RefreshSynthese(DataView dv)
        {
            int count = dv.Count;
            decimal production = SumCol(dv, "Production");
            decimal stockage = SumCol(dv, "Stockage");
            decimal autocons = SumCol(dv, "Autoconsommation");
            decimal consoBat = SumCol(dv, "Conso_Batterie");
            decimal consoReseau = SumCol(dv, "Conso_Reseau");
            decimal consoTotale = SumCol(dv, "Conso_Totale");
            decimal consoVerte = autocons + consoBat;

            DataGridSynthese.ItemsSource = new List<SyntheseRow>
            {
                new("Total période",
                    Fmt(production), Fmt(stockage), Fmt(consoVerte),
                    Fmt(consoReseau), Fmt(consoTotale)),
                new("Moy. journalière",
                    FmtMoy(production, count), FmtMoy(stockage, count),
                    FmtMoy(consoVerte, count), FmtMoy(consoReseau, count),
                    FmtMoy(consoTotale, count)),
            };
        }

        // ── Tableau 2 : ratios ───────────────────────────────────────────────
        private void RefreshRatios(DataView dv)
        {
            decimal production = SumCol(dv, "Production");
            decimal autocons = SumCol(dv, "Autoconsommation");
            decimal consoBat = SumCol(dv, "Conso_Batterie");
            decimal consoTotale = SumCol(dv, "Conso_Totale");
            decimal consoVerte = autocons + consoBat;

            DataGridRatios.ItemsSource = new List<RatiosRow>
            {
                new("Total période",
                    FmtPct(consoVerte, production),
                    FmtPct(consoVerte, consoTotale),
                    FmtPct(production,  consoTotale)),
            };
        }

        // ── Tableau 3 : simulations ──────────────────────────────────────────
        private void RefreshSimulations(DataView dv)
        {
            if (_currentTarif is null)
            {
                DataGridSimulations.ItemsSource = new List<SimulationRow>
            { new("–", "Tarif non disponible", "–", "–") };
                TxtSimulationSolaire.Text = "–";
                TxtSimulationAPayer.Text = "–";
                return;
            }

            decimal hp = _currentTarif.HP;
            decimal hc = _currentTarif.HC;
            decimal consoReseau = SumCol(dv, "Conso_Reseau");
            decimal autocons = SumCol(dv, "Autoconsommation");
            decimal consoBat = SumCol(dv, "Conso_Batterie");

            SimulationRow Calc(string libelle, decimal kwh, decimal pctHP, decimal pctHC)
            {
                decimal partHP = kwh * pctHP * hp;
                decimal partHC = kwh * pctHC * hc;
                return new(libelle, FmtEur(partHP), FmtEur(partHC), FmtEur(partHP + partHC));
            }

            decimal totalPrix = (consoReseau * 0.75m * hp) + (consoReseau * 0.25m * hc);
            decimal totalAutoCons = (autocons * 1.00m * hp) + (autocons * 0.00m * hc);
            decimal totalBat = (consoBat * 0.75m * hp) + (consoBat * 0.25m * hc);

            DataGridSimulations.ItemsSource = new List<SimulationRow>
            {
                Calc("Simulation Prix",       consoReseau, 0.75m, 0.25m),
                Calc("Simulation Auto conso", autocons,    1.00m, 0.00m),
                Calc("Simulation Batterie",   consoBat,    0.75m, 0.25m),
            };

            // Simulation solaire = Auto conso + Batterie (2 dernières lignes)
            decimal simulationSolaire = totalAutoCons + totalBat;
            // Simulation à payer = Prix + Auto conso + Batterie (3 lignes)
            decimal simulationAPayer = totalPrix + totalAutoCons + totalBat;

            TxtSimulationSolaire.Text = $"{FmtEur(simulationSolaire)} €";
            TxtSimulationAPayer.Text = $"{FmtEur(simulationAPayer)} €";
        }

        // ── Helpers calcul ───────────────────────────────────────────────────
        private decimal SumCol(DataView dv, string col)
        {
            if (_currentData == null || !_currentData.Columns.Contains(col)) return 0m;
            decimal acc = 0m;
            foreach (DataRowView rv in dv)
                if (rv.Row[col] != DBNull.Value)
                    acc += Convert.ToDecimal(rv.Row[col]);
            return acc;
        }

        private static string Fmt(decimal v) => v.ToString("F2");
        private static string FmtMoy(decimal v, int count) => count > 0 ? (v / count).ToString("F2") : "–";
        private static string FmtPct(decimal n, decimal d) => d == 0 ? "–" : (n / d * 100m).ToString("F1") + " %";
        private static string FmtEur(decimal v) => v.ToString("F2");

        // ── Colonnes masquées ────────────────────────────────────────────────
        private void AdjustColumns()
        {
            if (DataGridMeasures.Columns == null || DataGridMeasures.Columns.Count == 0) return;

            var hide = new[] { "Id_PrixElec", "Id_Mesure" };
            foreach (var c in DataGridMeasures.Columns)
            {
                var header = c.Header?.ToString() ?? string.Empty;
                if (hide.Any(h => string.Equals(h, header, StringComparison.OrdinalIgnoreCase)))
                    c.Visibility = Visibility.Collapsed;
            }

            var jourCol = DataGridMeasures.Columns.FirstOrDefault(c =>
                string.Equals((c.Header ?? "").ToString(), "Jour", StringComparison.OrdinalIgnoreCase));

            if (jourCol != null)
                Dispatcher.InvokeAsync(() => jourCol.DisplayIndex = 0,
                    System.Windows.Threading.DispatcherPriority.Background);
        }
    }

    internal record SyntheseRow(
        string Libelle, string Production, string Stockage,
        string ConsoVerte, string ConsoReseau, string ConsoTotale);

    internal record RatiosRow(
        string Libelle, string RatioVerteProd,
        string RatioVerteConso, string RatioProdConso);

    internal record SimulationRow(
        string Libelle, string HP, string HC, string Total);
}